---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ros2
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  selector:
    matchLabels:
      app: fleet-manager
  template:
    metadata:
      labels:
        app: fleet-manager
    spec:
      containers:
        - name: fleet-manager
          image: ghcr.io/ba23-robotic-fleet-management/ros2-fleet-manager:master
          env:
            - name: ZENO_DAEMON_ADDRESS
              value: tcp/zenoh-daemon:7447
          ports:
            - containerPort: 22011
          volumeMounts:
            - mountPath: /etc/zenoh-bridge-dds
              name: zenoh-bridge-conf
              readOnly: true
      volumes:
        - name: zenoh-bridge-conf
          configMap:
            defaultMode: 440
            name: zenoh-bridge-conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: ros2
  name: fleet-manager
spec:
  selector:
    app: fleet-manager
  ports:
    - protocol: TCP
      # Port exposed by the service
      port: 22011
      # Container port
      targetPort: 22011
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ros2
  name: zenoh-bridge-conf
data:
  config.json5: |
    {
      plugins: {
        dds: {
          domain: 1,
          fwd-discovery: true,
        },
      },
      mode: "client",
      connect: {
        endpoints: [
          "tcp/zenoh-daemon:7447"
        ]
      }
    }
